#include "stm32f4xx_hal.h"
#include "main.h"
#include "button.h"
uint8_t counter = 0;

uint32_t last_button_press = 0;
const uint32_t debounce_delay = 200;
const uint32_t led_blink_delay = 405;
//Button button;
uint32_t last_led_blink;
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
void update_leds(uint8_t value);

int main(void) {
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
   // Button_Init(&button, GIOA, GIPO_PIN_0, 200)
    uint32_t last_led_blink = HAL_GetTick();
    
    while (1) {
       /* if (HAL_GPIO_ReadPin(GPIOA, GPIO_PIN_0) == GPIO_PIN_RESET) {
            uint32_t current_time = HAL_GetTick();
            if ((current_time - last_button_press) > debounce_delay) {
                counter++;
                update_leds(counter);
                last_button_press = current_time;
            }
        }
        */
      if (button_release(GPIOA, GPIO_PIN_0, RESET))
       {
        counter++;
        update_leds(counter);
       }


        uint32_t current_time = HAL_GetTick();
        if ((current_time - last_led_blink) >= led_blink_delay) {
            HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
            last_led_blink = current_time;
        }
    }
}

void update_leds(uint8_t value) {
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_12, (value & 0x01) ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_13, (value & 0x02) ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, (value & 0x04) ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_15, (value & 0x08) ? GPIO_PIN_SET : GPIO_PIN_RESET);
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_8, (value & 0x10) ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

static void MX_GPIO_Init(void) {

    __HAL_RCC_GPIOB_CLK_ENABLE();
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    
    GPIO_InitStruct.Pin = GPIO_PIN_12 | GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    __HAL_RCC_GPIOA_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_0; // PIN BOTAO
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_PULLDOWN;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_8;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    // GPIO Initialization for on-board LED (GPIOC_PIN13)
    __HAL_RCC_GPIOC_CLK_ENABLE();
    GPIO_InitStruct.Pin = GPIO_PIN_13;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);
}

// System Clock Configuration (auto-generated by STM32CubeMX)
void SystemClock_Config(void) {
    // System Clock Configuration code
}
